apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: minio
  namespace: minio-system
spec:
  endpoints:
  - interval: 30s
    port: minio
  selector:
    matchLabels:
      app: minio-service
